name: integration_workflow



on:
  pull_request:
    branches: [ main ]

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - uses: RavenIntegrationTests/CompositeAction-Mock@v1

    - name: PrintEnv
      run: PrintEnv
    
    - name: Print pull request title
      run: echo "Pull request number is ${{ github.event.pull_request.title }}"
    
  
