name: integration_workflow



on:
  pull_request_target:
    branches: [ main ]

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - uses: RavenIntegrationTests/CompositeAction-Mock@v1
    - uses: RavenIntegrationTests/CompositeAction-Mock@main
      
    - name: print_env
      run: print_env
    
  second_job:
    runs-on: ubuntu-latest
    steps:

    - name: print_pull_request_title
      run: echo "Pull request title is ${{ github.event.pull_request.title }}"
  
